- name: Cart module
  hosts: cart
  become: yes
  tasks:

  - name: disable default  and enable nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs:18
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop
      state: present

  - name: remove the app directory if it presents
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create a app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the cart application code
    ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/cart.zip
    dest: /tmp

  - name: extact the cart.zip file to app directory
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies npm
    ansible.builtin.command: npm install

  - name: setup a new cart.service  in systemd
    ansible.builtin.copy: 
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: reaload the daemon
    ansible.builtin.systemd_service:
      daemon-reload: true

  - name: enable and start cart service
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: true
       