- name: catalogue installation
  hosts: catalogue
  become: yes
  tasks:
    - name: Disbling default version and enbaing Nodjs:18 version
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Disbling default version and enbaing Nodjs:18 version
      ansible.builtin.command: dnf module enable nodejs:18 -y
      
    - name: Installing nodejs:18
      ansible.builtin.dnf:
        name: nodejs
        state: present