- name: catalogue installation
  hosts: catalogue
  become: yes
  tasks:
    - name: Disbling default version Nodjs version
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enbaing Nodjs:18 version
      ansible.builtin.command: dnf module enable nodejs:18 -y
      
    - name: Installing nodejs:18
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: create a app directory
      ansible.builtin.file:
        path: /app
        state: directory