- name: user module
  hosts: user
  become: yes
  tasks: 
  - name: disable current default nodeJS version to Install
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:18 version
    ansible.builtin.command: dnf module enable nodejs:18 -y
    
  - name: installing nodejs:18
    ansible.builtin.dnf: 
      name: nodejs
      state: present
  
  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop
      state: present

  - name: remove app directory recursively it is already exists
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the application code
    ansible.builtin.command: curl -L -o /tmp/user.zip https://roboshop-builds.s3.amazonaws.com/user.zip
    
  - name: unzip the file to app directory
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    ansible.builtin.command: npm install
    args:
        chdir: /app

  - name: copy user service file into /etc/systemd/system/
    ansible.builtin.copy:
      src: /home/centos/roboshop-ansible/user.service
      dest: /etc/systemd/system/

  - name: reload daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  
  - name: copy mondb repo data
    ansible.builtin.copy:
      src: /home/centos/roboshop-ansible/mongo.repo
      dest: /etc/yum.repos.d/

  - name: install mongodb-org-shell
    ansible.builtin.dnf:
      name: mongodb-org-shell
      state: present

  - name: get the users count
    ansible.builtin.command:  mongo --host mongodb.madcheer.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  - name: Load the schema i.e users data
    ansible.builtin.shell: mongo --host mongodb.madcheer.online < /app/schema/user.js
    when: user_count.stdout == "0" # keep double quotes
 
  - name: enabale and start the user service
    ansible.builtin.service:
      state: started
      enabaled: yes